[project]
name = "chainlit-customized"
version = "0.1.0"
description = "Chainlit customization demo showcasing advanced UI/UX techniques"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chainlit>=2.6.4",
]
