[project]
user_env = []
session_timeout = 3600
user_session_timeout = 1296000
cache = false
allow_origins = [ "*",]

[features]
unsafe_allow_html = true
latex = false
user_message_autoscroll = true
auto_tag_thread = true
edit_message = true

[UI]
name = "Assistant"
layout = "wide"
cot = "full"
custom_js = "/public/themeToggle.js"
alert_style = "classic"
logo_file_url = ""
default_avatar_file_url = ""
default_theme = "light"

[meta]
generated_by = "2.6.4"

[features.spontaneous_file_upload]
enabled = true
accept = [ "*/*",]
max_files = 20
max_size_mb = 500

[features.audio]
sample_rate = 24000

[features.mcp.sse]
enabled = true

[features.mcp.streamable-http]
enabled = true

[features.mcp.stdio]
enabled = true
allowed_executables = [ "npx", "uvx",]
